spring:
  application:
    name: lnis
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false

management:
  endpoints:
    web:
      base-path: /lnis/api/v1/actuator
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
